Repository HACKTOBERFEST-2023-CHANDIGARH/web-dev-hactoberfest-2023, pull requests merged in 2023-10, with the labels that each got.

#14 created nft-component project
  easy/nft-preview-card-component-main/nft-preview-card-component-main-Sanskaari/.gitignore
  easy/nft-preview-card-component-main/nft-preview-card-component-main-Sanskaari/README.md
  easy/nft-preview-card-component-main/nft-preview-card-component-main-Sanskaari/dist/output.css
  easy/nft-preview-card-component-main/nft-preview-card-component-main-Sanskaari/images/favicon-32x32.png
  easy/nft-preview-card-component-main/nft-preview-card-component-main-Sanskaari/images/icon-clock.svg
  easy/nft-preview-card-component-main/nft-preview-card-component-main-Sanskaari/images/icon-ethereum.svg
  easy/nft-preview-card-component-main/nft-preview-card-component-main-Sanskaari/images/icon-view.svg
  easy/nft-preview-card-component-main/nft-preview-card-component-main-Sanskaari/images/image-avatar.png
  easy/nft-preview-card-component-main/nft-preview-card-component-main-Sanskaari/images/image-equilibrium.jpg
  easy/nft-preview-card-component-main/nft-preview-card-component-main-Sanskaari/images/nft-component-active.png
  easy/nft-preview-card-component-main/nft-preview-card-component-main-Sanskaari/images/nft-component-desktop.png
  easy/nft-preview-card-component-main/nft-preview-card-component-main-Sanskaari/images/nft-component-mobile.png
  easy/nft-preview-card-component-main/nft-preview-card-component-main-Sanskaari/index.html
  easy/nft-preview-card-component-main/nft-preview-card-component-main-Sanskaari/package-lock.json
  easy/nft-preview-card-component-main/nft-preview-card-component-main-Sanskaari/package.json
  easy/nft-preview-card-component-main/nft-preview-card-component-main-Sanskaari/src/input.css
  easy/nft-preview-card-component-main/nft-preview-card-component-main-Sanskaari/tailwind.config.js
Labels: changes-required

#18 Product preview card
  easy/product-preview-card-component-main/product-preview-card-component-main/product-preview-card-component-main-Anjali/README.md
  easy/product-preview-card-component-main/product-preview-card-component-main/product-preview-card-component-main-Anjali/images/favicon-32x32.png
  easy/product-preview-card-component-main/product-preview-card-component-main/product-preview-card-component-main-Anjali/images/icon-cart.svg
  easy/product-preview-card-component-main/product-preview-card-component-main/product-preview-card-component-main-Anjali/images/image-product-desktop.jpg
  easy/product-preview-card-component-main/product-preview-card-component-main/product-preview-card-component-main-Anjali/images/image-product-mobile.jpg
  easy/product-preview-card-component-main/product-preview-card-component-main/product-preview-card-component-main-Anjali/index.html
  easy/product-preview-card-component-main/product-preview-card-component-main/product-preview-card-component-main-Anjali/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#17 Fixed issue #6
  easy/results-summary-component-main/README-template.md
  easy/results-summary-component-main/Screenshot 2023-10-10 235637.png
  easy/results-summary-component-main/Screenshot 2023-10-11 000830.png
  easy/results-summary-component-main/Screenshot 2023-10-11 001243.png
  easy/results-summary-component-main/index.html
  easy/results-summary-component-main/style.css
Labels: hacktoberfest-accepted

#21 Medium/interactive comment section
  medium/interactive-comments-section-main/Interactive-comments-section-Sanskaari/.gitignore
  medium/interactive-comments-section-main/Interactive-comments-section-Sanskaari/README.md
  medium/interactive-comments-section-main/Interactive-comments-section-Sanskaari/app.js
  medium/interactive-comments-section-main/Interactive-comments-section-Sanskaari/data.json
  medium/interactive-comments-section-main/Interactive-comments-section-Sanskaari/images/avatars/image-amyrobson.png
  medium/interactive-comments-section-main/Interactive-comments-section-Sanskaari/images/avatars/image-amyrobson.webp
  medium/interactive-comments-section-main/Interactive-comments-section-Sanskaari/images/avatars/image-juliusomo.png
  medium/interactive-comments-section-main/Interactive-comments-section-Sanskaari/images/avatars/image-juliusomo.webp
  medium/interactive-comments-section-main/Interactive-comments-section-Sanskaari/images/avatars/image-maxblagun.png
  medium/interactive-comments-section-main/Interactive-comments-section-Sanskaari/images/avatars/image-maxblagun.webp
  medium/interactive-comments-section-main/Interactive-comments-section-Sanskaari/images/avatars/image-ramsesmiron.png
  medium/interactive-comments-section-main/Interactive-comments-section-Sanskaari/images/avatars/image-ramsesmiron.webp
  medium/interactive-comments-section-main/Interactive-comments-section-Sanskaari/images/comment-section-desktop.png
  medium/interactive-comments-section-main/Interactive-comments-section-Sanskaari/images/comment-section-mobile.png
  medium/interactive-comments-section-main/Interactive-comments-section-Sanskaari/images/favicon-32x32.png
  medium/interactive-comments-section-main/Interactive-comments-section-Sanskaari/images/icon-delete.svg
  medium/interactive-comments-section-main/Interactive-comments-section-Sanskaari/images/icon-edit.svg
  medium/interactive-comments-section-main/Interactive-comments-section-Sanskaari/images/icon-minus.svg
  medium/interactive-comments-section-main/Interactive-comments-section-Sanskaari/images/icon-plus.svg
  medium/interactive-comments-section-main/Interactive-comments-section-Sanskaari/images/icon-reply.svg
  medium/interactive-comments-section-main/Interactive-comments-section-Sanskaari/index.html
  medium/interactive-comments-section-main/Interactive-comments-section-Sanskaari/style.css
Labels: hacktoberfest-accepted
